--- # 
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <team>-karma
  namespace: <team>
  labels:
    app: <team>-karma
spec:
  selector:
    matchLabels:
      app: <team>-karma
  replicas: 1
  template:
    metadata:
      labels:
        app: <team>-karma
    spec:
      containers:
      - name: <team>-karma
        image: docker.io/ibmicpcoc/karma:latest
        imagePullPolicy: Always
        command: ["node", "app.js"]
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---
