--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab  17
--- # Stateful sets 
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: <team>-panda
  namespace: <team>
  labels:
    app: <team>-panda
spec:
  selector:
    matchLabels:
      app: <team>-panda
  replicas: 1
  serviceName: <team>-panda-server
  template:
    metadata:
      labels:
        app: <team>-panda
    spec:
      containers:
      - name: <team>-panda
        image: docker.io/ibmicpcoc/panda:latest
        imagePullPolicy: Always
        command: ["node", "app.js"]
        volumeMounts:
        - name: <team>-panda-d
          mountPath: /data
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
      restartPolicy: Always            
  volumeClaimTemplates:
  - metadata:
      name: <team>-panda-data
      namespace: <team>
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Mi
      storageClassName: rdb
---
