--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{team}}-doors
  namespace: {{team}}
  labels:
    app: {{team}}-doors
spec:
  selector:
    matchLabels:
      app: {{team}}-doors
  replicas: 1
  template:
    metadata:
      labels:
        app: {{team}}-doors
    spec:
      containers:
      - name: {{team}}-doors
        image: {{repoName}}/doors:last
        imagePullPolicy: Always
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: {{team}}-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: {{team}}-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---