--- # 
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <team>-lacey
  namespace: <team>
  labels:
    app: <team>-lacey
spec:
  selector:
    matchLabels:
      app: <team>-lacey
  replicas: 1
  template:
    metadata:
      labels:
        app: <team>-lacey
    spec:
      initContainers:
      - name: <team>-init
        image: centos:7
        command:
        - "bin/bash"
        - "-c"
        - "echo <team> > /data/<team>.txt"
        volumeMounts:
        - mountPath: /data
          name: config-data
      containers:
      - name: <team>-lacey
        image: docker.io/ibmicpcoc/lacey:latest
        imagePullPolicy: Always
        command: ["node", "app.js"]
        volumeMounts:
        - name: config-data
          mountPath: /data
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
      volumes:
      - name: config-data
      hostPath: "/data"
---
