--- #
--- # Course :: Problem Diagnosis and Troubleshooting Lab 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <team>-salty
  namespace: <team>
  labels:
    app: <team>-salty
spec:
  selector:
    matchLabels:
      app: <team>-salty
  replicas: 1
  template:
    metadata:
      labels:
        app: <team>-salty
    spec:
      containers:
      - name: <team>-salty
        image: docker.io/ibmicpcoc/salty:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4500
        env:
          - name: APP_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COLLECTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: COLLECTOR_CONFIG
          - name: INSTRUCTOR_CONFIG
            valueFrom: 
              configMapKeyRef:
                name: <team>-collector-config
                key: INSTRUCTOR_CONFIG
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
---
--- # Service defs
---
apiVersion: v1
kind: Service
metadata:
  name: <team>-salty
  namespace: <team>
  labels:
    app: <team>-salty
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 4500
      protocol: TCP
      name: <team>-salty
  selector:
    app: <team>-salty
---
